### ISSUE TITLE
Upgrade to paid plan: stuck with free plan

### ISSUE THREAD

**Issue by rmonnier** [keymetrics/keymetrics-support#145] opened 2018-02-01 16:35 UTC
Active subscription on stripe but stuck in free plan on the bucket.

**Comment by vmarchaud** [comment] 2018-02-01 16:47
Closing since it isnt reproductible, re-open if another customer have the problem.

**Closed by vmarchaud** 2018-02-01 16:47 UTC
Labels: backend, bug

**Comment by darioVD1206** [comment] 2024-12-05 13:37
Hi,

I’m encountering an issue with PM2 PLUS. Despite having an active subscription, my account still appears to be on the free plan. I’ve ensured my subscription is active, but the dashboard and CLI don’t reflect the upgrade.

Could you please assist me in resolving this issue? Let me know if there are any specific logs or configurations you’d like me to share.

Thank you for your help!

Best regards,
