### ISSUE TITLE
Server Deletion: Allow unlink from the dashboard

### ISSUE THREAD

**Issue by robin-monnier** [keymetrics/keymetrics-support#167] opened 2018-03-06 15:39 UTC
When using pm2 in a cloud providers, it would be much more convenient to unlink from the dashboard.

The delete server button is confusing as it doesn't seem to be restricted to already unlinked servers.

**Comment by vmarchaud** [comment] 2018-03-06 15:54
The issue is that with the current protocol we can't forbid PM2 to push data, so it will re-appear. Will need some refactor

**Comment by Unitech** [comment] 2018-03-07 17:33
Won't fix, never. This could cause an attacker to unlink all pm2 connected to keymetrics

**Closed** 2018-07-05 08:57 UTC
Labels: backend, feature request, frontend_v1
